- name: Check existence of matrix-maubot service
  stat:
    path: "/etc/systemd/system/matrix-maubot.service"
  register: matrix_maubot_service_stat
  when: "not matrix_maubot_enabled|bool"

- name: Ensure matrix-maubot is stopped
  service:
    name: matrix-maubot
    state: stopped
    daemon_reload: yes
  register: stopping_result
  when: "not matrix_maubot_enabled|bool and matrix_maubot_service_stat.stat.exists"

- name: Ensure matrix-maubot.service doesn't exist
  file:
    path: "/etc/systemd/system/matrix-maubot.service"
    state: absent
  when: "not matrix_maubot_enabled|bool and matrix_maubot_service_stat.stat.exists"

- name: Ensure systemd reloaded after matrix-maubot.service removal
  service:
    daemon_reload: yes
  when: "not matrix_maubot_enabled|bool and matrix_maubot_service_stat.stat.exists"

- name: Ensure maubot Docker image doesn't exist
  docker_image:
    name: "{{ matrix_maubot_docker_image }}"
    state: absent
  when: "not matrix_maubot_enabled|bool"
